name: ocr-service

services:
  ocr_service:
    build:
      context: ../
      args:
        - TESSDATA_PATH=tesseract
      dockerfile: Dockerfile
    image: ocr-service
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info,ocr_service=debug,tower_http=debug
      - SERVER_ENVIRONMENT=development
      - SERVICE_NAME=ocr-service
      - OTEL_ENABLED=false
      - TESSDATA_PATH=tesseract
