name: Pull Request Validation

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - Dockerfile
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - Dockerfile

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Lint with clippy
        run: cargo clippy

      - name: Run tests
        run: cargo test --verbose

      - name: Build
        run: cargo build --release
        if: github.ref == 'refs/heads/main'
